resources:
  - name: jfrogCliGit
    type: GitRepo
    configuration:
      path: yahavi/jfrog-cli
      gitProvider: myGitHub

pipelines:
  - name: JFrogCLI
    configuration:
      environmentVariables:
        readOnly:
          GO_VERSION: "1.13.7"
    steps:
      - name: Init
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: go
                versions:
                  - $GO_VERSION
          integrations:
            - name: myArtifactory
          inputResources:
            - name: jfrogCliGit
            
      - name: ArtifactoryTests
        type: Bash
        configuration:
          inputSteps:
            - name: Init
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -rt.url=$JFROG_CLI_RT_URL -rt.user=$JFROG_CLI_RT_USER -rt.password=$JFROG_CLI_RT_PASSWORD
      # - name: BintrayTests
      #   type: Bash
      #   configuration:
      #     runtime:
      #       type: image
      #       image:
      #         auto:
      #           language: go
      #           versions:
      #             - $GO_VERSION
      #     integrations:
      #       - name: myArtifactory
      #       - name: bintray
      #     inputResources:
      #       - name: jfrogCliGit
      #   execution:
      #     onExecute:
      #       - cd $res_jfrogCliGit_resourcePath
      #       - go test -v github.com/jfrog/jfrog-cli --timeout 0 -rt.url=$JFROG_CLI_RT_URL -rt.user=$JFROG_CLI_RT_USER -rt.password=$JFROG_CLI_RT_PASSWORD --bt.user=$int_bintray_user --bt.key=$int_bintray_key