resources:
  - name: jfrogCliGit
    type: GitRepo
    configuration:
      path: yahavi/jfrog-cli
      gitProvider: github

pipelines:
  # Global configuration
  - name: TestCLI
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: ecosysjfrog-docker-local.jfrog.io/jfrog-cli-test-image
            tag: 1.0.0
            registry: artifactory
      environmentVariables:
        readOnly:
          GOPROXY: https://gocenter.io
          SDKMAN_DIR: $res_jfrogCliGit_resourcePath/sdkman
          M2_HOME: $SDKMAN_DIR/candidates/maven/current

    steps:
      # Artifactory tests
      - name: Artifactory
        type: Bash
        configuration:
          integrations:
            - name: artifactory
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.artifactory -rt.url=$int_artifactory_url -rt.user=$int_artifactory_user -rt.password=$int_artifactory_apikey

      # Bintray tests
      - name: Bintray
        type: Bash
        configuration:
          integrations:
            - name: artifactory
            - name: bintray
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.bintray -rt.url=$int_artifactory_url -rt.user=$int_artifactory_user -rt.password=$int_artifactory_apikey --bt.user=$int_bintray_user -bt.key=$int_bintray_key

      # Npm tests
      - name: Npm
        type: Bash
        configuration:
          integrations:
            - name: artifactory
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - curl -sL https://deb.nodesource.com/setup_11.x | sudo bash -
            - sudo apt install nodejs
            - npm --version
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.npm -rt.url=$int_artifactory_url -rt.user=$int_artifactory_user -rt.password=$int_artifactory_apikey

      # Maven tests
      - name: Maven
        type: Bash
        configuration:
          integrations:
            - name: artifactory
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - mvn --version
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.maven -rt.url=$int_artifactory_url -rt.user=$int_artifactory_user -rt.password=$int_artifactory_apikey

      # Gradle tests
      - name: Gradle
        type: Bash
        configuration:
          integrations:
            - name: artifactory
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - gradle --version
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.gradle -rt.url=$int_artifactory_url -rt.user=$int_artifactory_user -rt.password=$int_artifactory_apikey

      # Go tests
      - name: Go
        type: Bash
        configuration:
          integrations:
            - name: artifactory
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go version
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.go -rt.url=$int_artifactory_url -rt.user=$int_artifactory_user -rt.password=$int_artifactory_apikey

      # Pip tests
      - name: Pip
        type: Bash
        configuration:
          integrations:
            - name: artifactory
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - pip --version
            - virtualenv .venv
            - source .venv/bin/activate
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.pip -rt.url=$int_artifactory_url -rt.user=$int_artifactory_user -rt.password=$int_artifactory_apikey

      # Distribution tests
      - name: Distribution
        type: Bash
        configuration:
          integrations:
            - name: artifactory
            - name: distribution
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.distribution -rt.url=$int_artifactory_url -rt.user=$int_artifactory_user -rt.password=$int_artifactory_apikey -rt.distUrl=$int_distribution_url
