resources:
  - name: jfrogCliGit
    type: GitRepo
    configuration:
      path: yahavi/jfrog-cli
      gitProvider: myGitHub

pipelines:
  - name: JFrogCLI
    configuration:
      environmentVariables:
        readOnly:
          COMMON_TESTS_ARGS: go test \-v github.com/jfrog/jfrog-cli --timeout 0 -rt.url=$JFROG_CLI_RT_URL -rt.user=$JFROG_CLI_RT_USER -rt.password=$JFROG_CLI_RT_PASSWORD
      runtime:
        type: image
        image:
          auto:
            language: go
            versions:
              - "1.13.7"
    
    steps:
      - name: ArtifactoryTests
        type: Bash
        configuration:
          integrations:
            - name: myArtifactory
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - $COMMON_TESTS_ARGS
      - name: BintrayTests
        type: Bash
        configuration:
          integrations:
            - name: myArtifactory
            - name: bintray
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 --rt.url=$JFROG_CLI_RT_URL -rt.user=$JFROG_CLI_RT_USER -rt.password=$JFROG_CLI_RT_PASSWORD --bt.user=$int_bintray_user --bt.key=$int_bintray_key