resources:
  - name: jfrogCliGit
    type: GitRepo
    configuration:
      path: yahavi/jfrog-cli
      gitProvider: myGitHub

pipelines:
  # Global configuration
  - name: TestCLI
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: go
            versions:
              - "1.13.7"
    
    steps:
      # Artifactory tests
      - name: Artifactory
        type: Bash
        configuration:
          integrations:
            - name: myArtifactory
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.artifactory -rt.url=$int_myArtifactory_url -rt.user=$int_myArtifactory_user -rt.password=$int_myArtifactory_apikey

      # Bintray tests
      - name: Bintray
        type: Bash
        configuration:
          integrations:
            - name: myArtifactory
            - name: bintray
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.bintray -rt.url=$int_myArtifactory_url -rt.user=$int_myArtifactory_user -rt.password=$int_myArtifactory_apikey --bt.user=$int_bintray_user -bt.key=$int_bintray_key

      # Npm tests
      - name: Npm
        type: Bash
        configuration:
          integrations:
            - name: myArtifactory
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.npm -rt.url=$int_myArtifactory_url -rt.user=$int_myArtifactory_user -rt.password=$int_myArtifactory_apikey