resources:
  - name: jfrogCliGit
    type: GitRepo
    configuration:
      path: yahavi/jfrog-cli
      gitProvider: myGitHub

pipelines:
  - name: JFrogCLI
    steps:
      - name: CliArtifactoryTests
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: go
                versions:
                  - "1.13.7"
          integrations:
            - name: myArtifactory
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli -test.artifactory --timeout 0 --rt.url=$int_myArtifactory_url --rt.user=$int_myArtifactory_user --rt.password=$int_myArtifactory_apikey

      - name: CliBintrayTests
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: go
                versions:
                  - "1.13.7"
          integrations:
            - name: myArtifactory
            - name: bintray
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli -test.bintray --timeout 0 --rt.url=$int_myArtifactory_url --rt.user=$int_myArtifactory_user --rt.password=$int_myArtifactory_apikey --bt.user=$int_bintray_user --bt.key=$int_binray_key