resources:
  - name: jfrogCliGit
    type: GitRepo
    configuration:
      path: yahavi/jfrog-cli
      gitProvider: github

pipelines:
  # Global configuration
  - name: TestCLI
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: yahavi/build-integration-env
            tag: 1.0.0
      environmentVariables:
        readOnly:
          GOPROXY: https://gocenter.io
          SDKMAN_DIR: $res_jfrogCliGit_resourcePath/sdkman
          M2_HOME: $SDKMAN_DIR/candidates/maven/current

    steps:
      # Artifactory tests
      - name: Artifactory
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.artifactory -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password_apikey

      # Bintray tests
      - name: Bintray
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.bintray -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password_apikey --bt.user=$int_jfrog_bintray_user -bt.key=$int_jfrog_bintray_key

      # Npm tests
      - name: Npm
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - npm --version
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.npm -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password_apikey

      # Maven tests
      - name: Maven
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - mvn --version
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.maven -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password_apikey

      # Gradle tests
      - name: Gradle
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - gradle --version
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.gradle -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_apikey

      # Go tests
      - name: Go
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go version
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.go -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password_apikey

      # Pip tests
      - name: Pip
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - pip --version
            - virtualenv .venv
            - source .venv/bin/activate
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.pip -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password_apikey

      # Distribution tests
      - name: Distribution
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli --timeout 0 -test.distribution -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password_apikey -rt.distUrl=$int_jfrog_dist_url

