resources:
  - name: jfrogCliGit
    type: GitRepo
    configuration:
      path: yahavi/jfrog-cli
      gitProvider: myGitHub

pipelines:
  - name: JFrogCLI
    steps:
      - name: ArtifactoryTests
        type: Bash
        configuration:
          environmentVariables:
            GOPATH:
            GOROOT:
          runtime:
            type: image
            image:
              auto:
                language: go
                versions:
                  - "1.13.7"
          environmentVariables:
            CI: "true"
          # integrations:
          #   - name: myArtifactory
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            # - unset GOROOT GOPATH
            - jfrog --version
            - cd $res_src_resourcePath
            - unset GOROOT GOPATH && go test -v github.com/jfrog/jfrog-cli -test.artifactory --timeout 0 --rt.url=int_myArtifactory_url --rt.user=int_myArtifactory_user --rt.password=int_myArtifactory_apikey